### ISSUE TITLE
Specify that login to docker hub is also necessary in this tutorial

### ISSUE THREAD

**Issue by bennythejudge** [IBM-Bluemix-Docs/containers#2256]
This tutorial: 

https://github.com/IBM-Bluemix-Docs/containers/blob/master/cs_tutorials_apps.md

requires login from the command line to Docker hub.

```
docker build -t registry.us-south.bluemix.net/sysdig-test/hello-world:1 .
Sending build context to Docker daemon  15.36kB
Step 1/6 : FROM node:9.4.0-alpine
Get https://registry-1.docker.io/v2/library/node/manifests/9.4.0-alpine: unauthorized: incorrect username or password
```

It's implicit but it's probably worth mentioning it especially for beginners.

**Comment by artberger** [comment]
@bennythejudge thanks for your feedback! We have revised the tutorial to use the IBM Cloud Container Registry (`ibmcloud cr`) CLI instead of `docker` due to some other changes in the works. Those docs are going out this week, and should address this issue. I'm going to close this here, but let us know if you need anything else!
