### ISSUE TITLE
Description about IBM Cloud Public in "Comparison of offerings and their combinations"

### ISSUE THREAD

**Issue by EunKyung-Kim** [IBM-Bluemix-Docs/containers#2367]
Hello,
I read https://cloud.ibm.com/docs/containers?topic=containers-cs_ov#differentiation
But, I'm confused about the desciption of IBM Cloud Public as follows.
>With IBM Cloud Public on shared or dedicated hardware or on bare metal machines, you can host your apps in clusters on the cloud by using IBM Cloud Kubernetes Service.

I can't differ between "IBM Cloud Public on dedicated hardware or bare metal machines" and " IBM Cloud Dedicated". Let me understand what's different point.

Thanks in advance,
EunKyung.

**Comment by Nadine2016** [comment]
@EunKyung-Kim thanks for commenting on the IBM Cloud docs. You can find the differences between running an IBM Cloud Kubernetes Service cluster on dedicated hardware vs. an IBM Cloud Dedicated cluster here https://cloud.ibm.com/docs/containers?topic=containers-dedicated#dedicated_environment

**Comment by Nadine2016** [comment]
@EunKyung-Kim you can choose to have a cluster with IBM Cloud Kubernetes Service that you own but where the hardware where the virtual machines run on are dedicated to you only. So in that case, IBM guarantees to not host virtual machines of other tenants on the same hardware. This option is more expensive than running your virtual machines on shared hardware. In IBM Cloud Dedicated, hardware is also dedicated to you only. But you have a contract with IBM that specifically outlines how your environment looks like. IBM owns and manages the machines for you. Because the environment is pre-configured in IBM Cloud Dedicated, you are limited to the features that you can have. For example, you cannot have a multizone cluster in Dedicated, but you can have it in IBM Cloud Public on dedicated hardware. I hope that helps? Let me know if you have further questions

**Comment by EunKyung-Kim** [comment]
Now I caught the different point~
Thank @Nadine2016 for letting me understand more clearly.
