### ISSUE TITLE
Installation of iks-charts/ibmcloud-alb-metrics-exporter fails in Multizone Cluster

### ISSUE THREAD

**Issue by teruz** [IBM-Bluemix-Docs/containers#2423]
The installation steps describe below,

> https://cloud.ibm.com/docs/containers?topic=containers-ingress_health&locale=en#ingress_monitoring

In the case of Multizone Cluster, 1st attempt is successful but 2nd attempts(another zone's ALB) is resulted in failure 
because of conflict of manifest names.

**Comment by teruz** [comment]
In detail, the name of ServiceAccount, ClusterRole and ClusterRoleBinding are embedded as constants. So, in the case of multiply installation of Helm conflicts.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.metricsNameSpace }}
  name: alb-metrics-service-account
imagePullSecrets:
  - name: bluemix-default-secret
  - name: bluemix-default-secret-regional
  - name: bluemix-default-secret-international
  - name: default-icr-io
  - name: kube-system-icr-io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alb-metrics-service-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alb-metrics-service-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: alb-metrics-service-account
    namespace: {{ .Values.metricsNameSpace }}
roleRef:
  kind: ClusterRole
  name: alb-metrics-service-cluster-role
  apiGroup: rbac.authorization.k8s.io

**Comment by Rachael-Graham** [comment]
Hello @teruz - apologies for the delay, but the Dev team has improved the chart so that you can specify the zone for the alb.

So, for example, if you have worker nodes in 2 zones in your cluster (like dal10 and dal 12), you could run these commands:
- `helm install iks-charts/ibmcloud-alb-metrics-exporter --set metricsNameSpace=kube-system --set name=alb-dal10-metrics-exporter --set albId=<alb_ID> --set albZone=dal10`
- `helm install iks-charts/ibmcloud-alb-metrics-exporter --set metricsNameSpace=kube-system --set name=alb-dal12-metrics-exporter --set albId=<alb_ID> --set albZone=dal12`

This should prevent naming conflicts. I am updating the documentation to reflect this change. Let me know if this works for you

**Comment by BonavincciAI2020** [comment]
heavy

**Comment by artberger** [comment]
Going to close this, but let us know if you have any further feedback. Thanks!
